#!/usr/bin/env bash
set -euo pipefail

BASE_URL=${1:-http://127.0.0.1:8000}
SESSION_PREFIX=${2:-semantic-smoke-merged}
COUNTER=0

ask() {
  local msg="$1"
  COUNTER=$((COUNTER + 1))
  local session_id="${SESSION_PREFIX}-${COUNTER}"
  echo "\n> $msg"
  curl -s "$BASE_URL/chat" \
    -H 'Content-Type: application/json' \
    -d "{\"session_id\": \"$session_id\", \"message\": \"$msg\"}" | sed 's/^/  /'
}

# Odpiralni čas & splošno
ask "Kdaj ste odprti?"
ask "Ob kateri uri odprete?"
ask "Ali ste odprti ob ponedeljkih?"
ask "Ste odprti ob nedeljah?"
ask "Kakšen je vaš delovni čas?"
ask "Do kdaj ste odprti v soboto?"
ask "Ali imate odprto za praznike?"
ask "Kdaj je zadnji prihod na kosilo?"
ask "Ali moram rezervirati vnaprej?"
ask "Lahko pridem brez rezervacije?"

# Zajtrk
ask "Kaj je za zajtrk?"
ask "Ob kateri uri je zajtrk?"
ask "Ali je zajtrk vključen v ceno?"
ask "Kaj ponujate za zajtrk?"
ask "Ali imate domač zajtrk?"
ask "Je zajtrk bufet ali serviran?"
ask "Imate brezglutenski zajtrk?"
ask "Kaj dobim za zajtrk?"
ask "Ali je zajtrk obvezen?"
ask "Koliko stane zajtrk?"

# Večerja & hrana
ask "Koliko stane večerja?"
ask "Ob kateri uri je večerja?"
ask "Kaj je za večerjo?"
ask "Ali ponujate večerjo?"
ask "Imate vegetarijansko hrano?"
ask "Ali imate brezglutensko hrano?"
ask "Kaj je na jedilniku?"
ask "Kakšna je vikend ponudba?"
ask "Koliko stane kosilo?"
ask "Kaj ponujate za kosilo ob vikendih?"
ask "Imate degustacijski meni?"
ask "Koliko hodov ima degustacijski meni?"
ask "Ali prilagodite hrano za alergike?"
ask "Imate vegansko hrano?"
ask "Ali strežete večerjo ob ponedeljkih?"
ask "Jedilnik?"
ask "Kaj ponujate za kosilo?"

# Sobe & nastanitev
ask "Koliko sob imate?"
ask "Koliko stane nočitev?"
ask "Katere sobe imate?"
ask "Koliko stane soba za 2 osebi?"
ask "Imate družinsko sobo?"
ask "Ali imajo sobe balkon?"
ask "Imate klimatizirane sobe?"
ask "Ali je v sobi wifi?"
ask "Kdaj je prijava?"
ask "Kdaj je odjava?"
ask "Koliko nočitev moram rezervirati?"
ask "Kakšna je minimalna nočitev poleti?"
ask "Ali sprejemete hišne ljubljenčke?"
ask "Lahko pridem s psom?"
ask "Kako plačam?"
ask "Ali sprejemate kartice?"
ask "Imate parkirišče?"
ask "Je parking brezplačen?"
ask "Kaj je vključeno v ceno sobe?"
ask "Katera soba je najboljša za družino?"
ask "Koliko oseb gre v eno sobo?"
ask "Ali je zajtrk vključen?"

# Družina & kmetija
ask "Kdo je gospodar kmetije?"
ask "Povejte mi o družini."
ask "Kdo je Aljaž?"
ask "Kdo je Barbara?"
ask "Kdo kuha pri vas?"
ask "Kdo je Angelca?"
ask "Kako dolgo imate kmetijo?"
ask "Koliko zemlje imate?"
ask "Kakšne živali imate?"
ask "Ali imate krave?"
ask "Lahko otroci vidijo živali?"
ask "Ali lahko božamo zajčke?"
ask "Imate konje?"
ask "Ali lahko jahamo?"
ask "Koliko stane jahanje s ponijem?"
ask "Kdo ste vi?"
ask "Kdo je Julija?"
ask "Kdo je Ana?"

# Lokacija & kontakt
ask "Kje ste?"
ask "Kakšen je vaš naslov?"
ask "Kako vas najdem?"
ask "Koliko ste oddaljeni od Maribora?"
ask "Imate telefon?"
ask "Kakšna je vaša telefonska številka?"
ask "Kakšen je vaš email?"
ask "Na kateri nadmorski višini ste?"
ask "Kako pridem do vas z avtom?"
ask "Imate koordinate za GPS?"
ask "Kako vas najdemo"
ask "Kakšen je naslov"

# Izdelki & trgovina
ask "Kaj prodajate?"
ask "Imate marmelado?"
ask "Katere marmelade imate?"
ask "Koliko stane marmelada?"
ask "Imate domač liker?"
ask "Koliko stane borovničev liker?"
ask "Prodajate bunko?"
ask "Koliko stane pohorska bunka?"
ask "Imate domačo salamo?"
ask "Kje lahko kupim vaše izdelke?"
ask "Ali imate spletno trgovino?"
ask "Prodajate gibanico?"
ask "Kako naročim izdelke?"
ask "Imate darilne bone?"
ask "Koliko stane darilni bon?"
ask "Ali lahko kupim izdelke preko spleta?"

# Vina
ask "Kakšna vina imate?"
ask "Imate vinsko karto?"
ask "Ali ponujate vinsko spremljavo?"
ask "Ali imate lokalna vina?"

# Izleti & okolica
ask "Kaj je v okolici?"
ask "Kam na izlet?"
ask "Kakšen izlet priporočate v bližini?"
ask "Kako pridem do Areha?"
ask "Kako pridem v Rače?"

# Rezervacije
ask "Rad bi rezerviral sobo za vikend."
ask "Ali lahko rezerviram sobo?"
ask "Rad bi rezerviral mizo to nedeljo ob 13:00."
ask "Rezervacija mize za 4 osebe v soboto."

# Praznovanja & dogodki
ask "Organizirate rojstne dneve?"
ask "Lahko praznujemo obletnico pri vas?"
ask "Imate prostor za poroko?"
ask "Koliko stane najem prostora?"
ask "Ali organizirate teambuilding?"
ask "Lahko pripravite pogrebščino?"
ask "Imate prostor za 30 oseb?"
ask "Koliko ljudi lahko sprejmete?"
ask "Kakšna je kapaciteta jedilnice?"
ask "Imate prostor za poslovni sestanek?"
ask "Lahko organiziramo piknik?"
ask "Imate zunanji prostor za praznovanje?"
ask "Ali pripravljate silvestrovo?"
ask "Imate božični meni?"
ask "Kaj ponujate za valentinovo?"

# Otroci & družine
ask "Je kmetija primerna za otroke?"
ask "Imate igrišče za otroke?"
ask "Kaj lahko otroci počnejo pri vas?"
ask "Ali imate otroški meni?"
ask "Koliko stane otrok?"
ask "Do koliko let je otrok zastonj?"
ask "Imate otroški stol?"
ask "Ali imate previjalno mizo?"
ask "Je varno za malčke?"
ask "Kaj ponujate za dojenčke?"
ask "Imate posteljo za dojenčka?"
ask "Lahko otroci pomagajo na kmetiji?"
ask "Ali imate kotiček za otroke?"
ask "Je primerno za 3-letnika?"
ask "Imate animacije za otroke?"

# Vreme & sezona
ask "Kaj počnemo če dežuje?"
ask "Imate notranjo jedilnico?"
ask "Ali je terasa pokrita?"
ask "Kdaj je najboljši čas za obisk?"
ask "Katera sezona je najlepša?"
ask "Ali ste odprti pozimi?"
ask "Imate gretje?"
ask "Je poleti vroče v sobah?"
ask "Kako je jeseni pri vas?"
ask "Ali imate sneg pozimi?"

# Dostop & transport
ask "Kako pridem z avtobusom?"
ask "Imate postajališče za avtodome?"
ask "Lahko pridem s kolesom?"
ask "Koliko je od avtoceste?"
ask "Je cesta asfaltirana?"
ask "Ali pridete po nas na postajo?"
ask "Imate transfer iz letališča?"
ask "Kako daleč je Ljubljana?"
ask "Koliko časa traja vožnja iz Celja?"
ask "Je primerno za motoriste?"

# Romantika & pari
ask "Imate romantično sobo?"
ask "Lahko pripravite romantično večerjo?"
ask "Imate jacuzzi?"
ask "Ali imate savno?"
ask "Je primerno za medene tedne?"
ask "Lahko dobim sobo s pogledom?"
ask "Imate šampanjec?"
ask "Lahko pripravite presenečenje za partnerja?"
ask "Imate masažo?"
ask "Kaj priporočate za parček?"

# Aktivnosti & šport
ask "Kje lahko hodimo?"
ask "Imate pohodne poti?"
ask "Koliko je do Areha?"
ask "Lahko grem na smučanje?"
ask "Kje je najbližje smučišče?"
ask "Imate kolesa za izposojo?"
ask "Je primerno za kolesarje?"
ask "Kje lahko plavamo?"
ask "Imate bazen?"
ask "Kje je najbližje jezero?"
ask "Lahko grem na ribolov?"
ask "Imate e-kolesa?"
ask "Kje je golf igrišče?"
ask "Ali organizirate vodene ture?"
ask "Imate nordijsko hojo?"

# Tehnologija & udobje
ask "Imate televizijo v sobi?"
ask "Je wifi hiter?"
ask "Imate Netflix?"
ask "Lahko delam od doma pri vas?"
ask "Imate prostor za delo?"
ask "Ali imate tiskanje?"
ask "Je signal dober?"
ask "Imate polnilec za telefon?"
ask "Lahko napolnim električni avto?"
ask "Imate polnilnico za EV?"

# Posebne zahteve
ask "Imate halal hrano?"
ask "Ali pripravljate košer hrano?"
ask "Imate hrano za diabetike?"
ask "Kaj če sem alergičen na oreščke?"
ask "Ali imate brezalkoholno pijačo?"
ask "Imate pivo?"
ask "Kakšne sokove imate?"
ask "Imate kavo?"
ask "Ali imate čaj?"
ask "Lahko dobim mleko brez laktoze?"
